version: "2"

networks:
  example_app:

services:
  mongo.example.app:
    image: mongo:4.2.0
    ports:
      - "27017:27017"
    networks:
      - example_app

  web.example.app:
    build:
      dockerfile: ./docker/Dockerfile
      context: ..
      args:
        - NODE_VERSION=12.10.0
        - YARN_VERSION=1.17.3
    environment:
      - PORT=3000
      - ADMIN_EMAIL=admin@example.com
      - ADMIN_PASSWORD=password
      - JWT_SECRET=jwt-secret
      - MONGO_LOCATION=mongo.example.app
      - MONGO_PORT=27017
      - MONGO_NAME=example
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
      - EMAIL_FROM=${EMAIL_FROM}
    ports:
      - "3000:3000"
    depends_on:
      - mongo.example.app
    networks:
      - example_app
